### PR TITLE
These commits fix the Makefile and a little typo in the POD

### PR DESCRIPTION
**Pull request by ology**

### CODE REVIEW

**Comment by tobyink** [comment]
Don't lines need to be prefixed with whitespace in pod preformatted sections?

**Comment by ology** [comment]
Yes. The Makefile example lines are prefixed with a single space. (Two spaces works to make it verbatim text, too.)

**Comment by ology** [comment]
Guess I forgot to mention that the Makefile needed literal tab characters instead of spaces.

**Comment by tobyink** [comment]
I'd like to keep the whitespace as it is in the pod, but it would be a good idea to include an actual working `examples/` dir in the distribution, including Makefile, packages.json, config files, and a few pages.

**Comment by ology** [comment]
I believe it is a mistake to include a non-functional Makefile example in your POD. I copy-pasted initially, and was stumped for a day. Makefiles need literal tabs, not spaces. That was the nature of this PR.

**Comment by tobyink** [comment]
I've included a fully functional example, including a working Makefile, in the latest release:

https://metacpan.org/release/TOBYINK/Web-PerlDistSite-0.001007/source/examples/site1

**Comment by ology** [comment]
Excellent. `eg/` & `examples/` directories are where it's at. :-)

**Pull request closed without merging**
